### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by carrineblank** [carrineblank/MicrO#1]
1.  Logical axioms for three classes of microbiological culture media are not functioning.

2.  There are a number of new terms that are being requested for entry into ChEBI.  Temporary terms are located under the class "ChEBI terms to be added and processed"

3.  External ontologies are currently being imported using temporary owl files (created by OntoFox) in the "MicrO and Import Modules" folder.  Once the domain name request has been approved and purl addresses assigned, these will be replaced.

**Comment by cmungall** [comment]
Do you have a link to the CHEBI tracker number?

For the owl files, you can still go ahead and use whatever URI you like and resolve imports using a catalog file

**Comment by carrineblank** [comment]
I just submitted the request to ChEBI.

The tracker number is:

[chebi:curator-requests] #2466
