### ISSUE TITLE
Duplication of 'environmental material'

### ISSUE THREAD

**Issue by pbuttigieg** [carrineblank/MicrO#11]
Hello!
Looks like you have a duplication of `environmental material`
![capture](https://cloud.githubusercontent.com/assets/2276146/11798052/bb21d38a-a2c7-11e5-821b-561e51820b8c.PNG)

The one asserted under `environmental feature` should be removed along with its subclasses.

**Comment by carrineblank** [comment]
Thanks for noting that!  The fix has been made and will be reflected when the next version of MicrO is released.
