### ISSUE TITLE
Multiple inheritance: habitat (ENVO_00002036)

### ISSUE THREAD

**Issue by pbuttigieg** [carrineblank/MicrO#15]
Seems like there's a MICRO assertion that a `habitat` is a `biome`, which isn't the intended semantics in ENVO. This also creates avoidable multiple inheritance.

![capture](https://cloud.githubusercontent.com/assets/2276146/11799211/4ef5fcd0-a2d2-11e5-87a5-99214f1d187f.PNG)

**Comment by carrineblank** [comment]
Not sure how that happened, so thanks for noting that!

This has been fixed, and will be reflected in the next release of MicrO.
