### ISSUE TITLE
Punning are preventing from importing terms from MicrO

### ISSUE THREAD

**Issue by citmejia** [carrineblank/MicrO#21]
Hi,

There are a number of Illegal redeclarations of entities in MicrO. This is preventing me from using robot to extract and merge terms from MicrO.

**Comment by carrineblank** [comment]
Hello citmejia,

Can you give me some suggestions (is there any information as to which classes are leading to the violations in any error messages) as to wha<https://messaging.umt.edu/owa/?ae=Item&t=IPM.Note&id=RgAAAAD4RdV%2fyzI9TYnFZFnQVrOLBwAUvKOMtIvpQKuYPZUAYfp6AAAARngxAAByfrDFM%2bH5RoYtnK6Vgz23AAHPTk6aAAAJ&a=Reply&cb=0&pspid=_1528831151006_321333201#>t might be causing the errors to help point me towards fixing the problem?

Thanks,

-Carrine


Carrine E. Blank, PhD
Research Assistant Professor
109A Clapp Science Building
Department of Geosciences
University of Montana
32 Campus Drive
Missoula, MT 59812-1296
406-880-3402 (cell); carrine.blank (Skype); carrine.blank@umontana.edu (email)
http://hs.umt.edu/geosciences/people/research.php?s=Blank1937
________________________________

**Comment by citmejia** [comment]
Hi Carrine,

I copy and paste the errors thrown by the robot. Basically, MicrO is
currently using the same IRI either for an annotation property and an
object property, or for a data property and an annotation property.

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Synonym in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Synonym>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Synonym>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_Name in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_Name>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_Name>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Display_Name in punning not
allowed [Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Display_Name>)),
Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Display_Name>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#UMLS_CUI in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#UMLS_CUI>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#UMLS_CUI>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_CUI in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_CUI>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_CUI>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_DUI in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_DUI>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_DUI>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#NUI in punning not allowed
[Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#NUI>)),
Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#NUI
>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Name in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Name>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Name>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_CUI in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_CUI>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_CUI>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Definition in punning
not allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Definition>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Definition>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/OBI_0000293 in punning not allowed
[Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/OBI_0000293>)),
Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/OBI_0000293>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/OBI_0000299 in punning not allowed
[Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/OBI_0000299>)),
Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/OBI_0000299
>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/BFO_0000054 in punning not allowed
[Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/BFO_0000054>)),
Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000054>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/RO_0002526 in punning not allowed
[Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002526>)),
Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002526
>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/RO_0002303 in punning not allowed
[Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002303>)),
Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002303>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/BFO_0000055 in punning not allowed
[Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/BFO_0000055>)),
Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000055>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/RO_0002576 in punning not allowed
[Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002576>)),
Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002576>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/RO_0002220 in punning not allowed
[Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002220>)),
Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002220
>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/RO_0002509 in punning not allowed
[Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002509>)),
Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002509
>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/RO_0002526 in punning not allowed
[Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002526>)),
Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002526
>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#UMLS_CUI in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#UMLS_CUI>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#UMLS_CUI>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/RO_0002303 in punning not allowed
[Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002303>)),
Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002303>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_DUI in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_DUI>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_DUI>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_CUI in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_CUI>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_CUI>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/RO_0002509 in punning not allowed
[Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002509>)),
Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002509
>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_Name in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_Name>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_Name>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/OBI_0000293 in punning not allowed
[Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/OBI_0000293>)),
Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/OBI_0000293>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_CUI in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_CUI>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_CUI>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/MICRO_0001199 in punning not allowed
[Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/MICRO_0001199>)),
Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/MICRO_0001199
>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/OBI_0000299 in punning not allowed
[Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/OBI_0000299>)),
Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/OBI_0000299
>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Definition in punning
not allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Definition>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Definition>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/MICRO_0001218 in punning not allowed
[Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/MICRO_0001218>)),
Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/MICRO_0001218
>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/BFO_0000054 in punning not allowed
[Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/BFO_0000054>)),
Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000054>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Display_Name in punning not
allowed [Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Display_Name>)),
Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Display_Name>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/BFO_0000055 in punning not allowed
[Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/BFO_0000055>)),
Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000055>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/RO_0002576 in punning not allowed
[Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002576>)),
Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002576>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#NUI in punning not allowed
[Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#NUI>)),
Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#NUI
>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Synonym in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Synonym>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Synonym>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/MICRO_0001462 in punning not allowed
[Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/MICRO_0001462>)),
Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/MICRO_0001462
>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/MICRO_0001463 in punning not allowed
[Declaration(AnnotationProperty(<
http://purl.obolibrary.org/obo/MICRO_0001463>)),
Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/MICRO_0001463>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/MICRO_0001205 in punning not allowed
[Declaration(AnnotationProperty(<
http://purl.obolibrary.org/obo/MICRO_0001205>)),
Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/MICRO_0001205>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.obolibrary.org/obo/RO_0002220 in punning not allowed
[Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002220>)),
Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002220
>))]

ERROR Illegal redeclarations of entities: reuse of entity
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Name in punning not
allowed [Declaration(DataProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Name>)),
Declaration(AnnotationProperty(<
http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Name>))]


Best,

Citlalli


2018-06-12 14:20 GMT-05:00 Carrine Blank <notifications@github.com>:

**Comment by carrineblank** [comment]
ΟΚ, thanks for the information Citlalli,

I'll try to identify what the problem is in the next day or so.


-Carrine


Carrine E. Blank, PhD
Research Assistant Professor
109A Clapp Science Building
Department of Geosciences
University of Montana
32 Campus Drive
Missoula, MT 59812-1296
406-880-3402 (cell); carrine.blank (Skype); carrine.blank@umontana.edu (email)
http://hs.umt.edu/geosciences/people/research.php?s=Blank1937
________________________________

**Comment by carrineblank** [comment]
Hi Citlalli,

I found 6 duplicate classes (not sure how that happened - they were in the same location of the owl file so some bug must have appeared at some point; five duplicates were MicrO classes and one was an RO class).  The duplicate classes were removed and I've uploaded what is now the current version of MicrO (should be version 1.5.1).   I can't push to github at present due to the dreaded tlsv1 alert protocol version error, and I've spent two days trying to work around that error.  Luckily, I managed to upload the new files onto GitHub manually so you should be good-to-go.

Let me know if you have any additional issues.....

Thanks for alerting me to the errors!

-Carrine

**Comment by citmejia** [comment]
Hello Carrine,

I forked and cloned your repo, and I managed to fix MicrO. I had to change
some imports declarations, since most "illegal reuse of entities" happened
in properties imported from RO, OBI, and NDF-RT. What I did was:

1) Conflictual imports from RO and OBI were some object properties that
used the same IRI as some annotation properties. I deleted annotation
properties to preserve relations between classes using those object
properties. As result, all metadata of the object properties (label,
definition, etc.) was lost. Thus, I extracted corresponding terms from
original ontologies and merged them with MicrO. Almost everything was
restored except for metadata of BFO_0000055 and BFO_0000054.

2) Conflictual imports from NDF-RT were some data properties that used the
same IRI as some annotation properties. I deleted data properties to
preserve metadata of classes that used corresponding annotation properties.
However, in NDF-RT, these were actually data properties. So I don't know if
there is going to be a problem.

3) There were a few MicrO object properties that were also annotation
properties. I deleted annotation properties and fixed by hand the metadata
of corresponding object properties.

You can take a look at the result in my forked repo and see if it helps.

I'm going to try your new version too.


Best,
Citlalli





2018-06-12 15:38 GMT-05:00 Carrine Blank <notifications@github.com>:

**Comment by carrineblank** [comment]
Hi Citlalli,

Thanks so much for your message; I haven't updated any of the ontology imports in over 6 months and if they have undergone major changes (which they often do) then I haven't been able to keep up with those.  Hopefully we can get some funding in the future to further develop and build up MicrO and then these can be fixed; in the meantime all I am able to manage are some quick fixes here and there.

Best wishes on your project!  If there is anything else I can do for you let me know.....

-Carrine
