### ISSUE TITLE
Fix IRIs of imported ontology subsets

### ISSUE THREAD

**Issue by rlwalls2008** [carrineblank/MicrO#5]
The imported ontologies still have ontofox IRIs, so they don't resolve when the ontology is opened in Protege. They should either use obo foundry purls or direct links to the github location.

**Comment by rlwalls2008** [comment]
I think this one is really important to fix before the masuscript is reviewed!  @carrineblank  Do you have time to work on this with me over the weekend?

**Comment by rlwalls2008** [comment]
I think it  would be better to name the import files something like go_imports.owl or go_micro.owl rather than GO.owl, so as to avoid confusion with the original go.owl file that contains the Gene Ontology.

**Comment by rlwalls2008** [comment]
We can fix this now by using the github IRIs for import files while we wait for the OBO Foundry YAML file to be generated for editing PURLs 
OBOFoundry/OBOFoundry.github.io#147

**Comment by carrineblank** [comment]
Renamed import files to BSPO_imports.owl (etc).

**Comment by carrineblank** [comment]
Replaced file imports with URL imports using the GitHub url addresses.

**Comment by carrineblank** [comment]
Issues have been corrected.
