### ISSUE TITLE
develop a set of editing and release SOPs

### ISSUE THREAD

**Issue by rlwalls2008** [carrineblank/MicrO#6]
You can look at what BCO does (https://github.com/tucotuco/bco/wiki), but that is only partially worked out and still has lots of manual steps. Probably better for us to look at what ENVO is doing and try to emulate some of that. We don't have to do it all at once, but we will at least need a basic release policy for the publication submission.

**Comment by pbuttigieg** [comment]
@cmungall and I are working on streamlining this - perhaps we can link up our efforts?

**Comment by pbuttigieg** [comment]
Also, there seem to be cases of duplicated subclass assertions: one made in MICRO, the other in the imported ontology. Many reference the same superclass, but some lead to multiple inheritance:

![capture](https://cloud.githubusercontent.com/assets/2276146/11798671/498bf272-a2cd-11e5-8511-b5b38f3d1796.PNG)

In this case (for `guar gum`), I would consider asking if OBI would surrender this class to either CHEBI or ENVO (depending on what exactly it means) so you can work with the imported hierarchy without having to assert a new superclass.

**Comment by carrineblank** [comment]
The to-be-handled queues in the OWL file are temporary, and all have now been requested new classes for ChEBI (submitted in both October and earlier in January).  As soon as the classes are in ChEBI these will disappear.  These classes do not have MicrO ID's; rather they have temporary ID's.

**Comment by carrineblank** [comment]
Inheritance for guar gum was corrected.  I haven't intentionally changed the superclasses for imported terms, so most likely it that something has occurred during the importation process in past versions of MicrO that has caused this.  I will keep an eye out for this, and I appreciate you bringing it to my attention!  The change will be reflected in the new release of MicrO (upcoming).
