### ISSUE TITLE
replace # in term IRIs with /

### ISSUE THREAD

**Issue by rlwalls2008** [carrineblank/MicrO#8]
I can change the prefix for all IRIs at once in Protege, but cannot switch from # to /. This will have to be done in text editor and then check, unless there is a way to do it with owlapi

**Comment by rlwalls2008** [comment]
Also, term IRIs should be of the form http://purl.obolibrary.org/obo/MICRO_0000000, rather than MicrO_0000000.

**Comment by carrineblank** [comment]
IRI format has been changed to http:/purl.obolibrary.org/obo/MICRO_.......
