### ISSUE TITLE
Terms with incorrect IRIs

### ISSUE THREAD

**Issue by rlwalls2008** [carrineblank/MicrO#9]
There are a number of MicrO classes and properties that have incorrect IRI prefixes. For example:

http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MicrO_0001246 
http://purl.org/obo/owl/OBO_REL#MicrO_0001318

There aren't that many of them, so probably best to fix by hand.

**Comment by carrineblank** [comment]
IRIs fixed!
